"""Phase 0 Canonical Models

Revision ID: 1f8282c9afbb
Revises: 875678a53be5
Create Date: 2026-02-14 09:01:10.838803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f8282c9afbb'
down_revision: Union[str, Sequence[str], None] = '875678a53be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums first
    jurisdiction_enum = postgresql.ENUM('USPTO', 'EPO', 'WIPO', name='jurisdictionenum')
    jurisdiction_enum.create(op.get_bind())
    
    matter_type_enum = postgresql.ENUM('UTILITY', 'DESIGN', 'PLANT', 'PROVISIONAL', name='mattertypeenum')
    matter_type_enum.create(op.get_bind())
    
    op.create_table('brief_versions',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_material_hash', sa.String(), nullable=True),
    sa.Column('is_authoritative', sa.Boolean(), nullable=True),
    sa.Column('structure_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_versions_matter_id'), 'brief_versions', ['matter_id'], unique=False)
    op.create_table('spec_versions',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('format_style', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spec_versions_matter_id'), 'spec_versions', ['matter_id'], unique=False)
    op.create_table('workstreams',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('workstream_type', sa.Enum('DRAFTING_APPLICATION', 'OFFICE_ACTION_RESPONSE', 'IDR_REVIEW', name='workstreamtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'ON_HOLD', 'COMPLETED', name='workstreamstatusenum'), nullable=False),
    sa.Column('active_brief_version_id', sa.UUID(), nullable=True),
    sa.Column('active_claim_version_id', sa.UUID(), nullable=True),
    sa.Column('active_spec_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_brief_version_id'], ['brief_versions.id'], ),
    sa.ForeignKeyConstraint(['active_claim_version_id'], ['claim_graph_versions.id'], ),
    sa.ForeignKeyConstraint(['active_spec_version_id'], ['spec_versions.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workstreams_matter_id'), 'workstreams', ['matter_id'], unique=False)
    op.create_index(op.f('ix_claim_graph_versions_matter_id'), 'claim_graph_versions', ['matter_id'], unique=False)
    op.drop_constraint(op.f('claim_graph_versions_created_by_id_fkey'), 'claim_graph_versions', type_='foreignkey')
    op.drop_column('claim_graph_versions', 'created_by_id')
    op.add_column('matters', sa.Column('jurisdiction', sa.Enum('USPTO', 'EPO', 'WIPO', name='jurisdictionenum'), nullable=False, server_default='USPTO'))
    op.add_column('matters', sa.Column('matter_type', sa.Enum('UTILITY', 'DESIGN', 'PLANT', 'PROVISIONAL', name='mattertypeenum'), nullable=False, server_default='UTILITY'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matters', 'matter_type')
    op.drop_column('matters', 'jurisdiction')
    
    # Drop Enums
    sa.Enum(name='mattertypeenum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='jurisdictionenum').drop(op.get_bind(), checkfirst=False)
    
    op.add_column('claim_graph_versions', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('claim_graph_versions_created_by_id_fkey'), 'claim_graph_versions', 'users', ['created_by_id'], ['id'])
    op.drop_index(op.f('ix_claim_graph_versions_matter_id'), table_name='claim_graph_versions')
    op.drop_index(op.f('ix_workstreams_matter_id'), table_name='workstreams')
    op.drop_table('workstreams')
    op.drop_index(op.f('ix_spec_versions_matter_id'), table_name='spec_versions')
    op.drop_table('spec_versions')
    op.drop_index(op.f('ix_brief_versions_matter_id'), table_name='brief_versions')
    op.drop_table('brief_versions')
    # ### end Alembic commands ###
