"""add tenant_llm_config

Revision ID: 3340ae9bbdc1
Revises: 7edb7006f903
Create Date: 2026-02-22 20:10:12.543039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3340ae9bbdc1'
down_revision: Union[str, Sequence[str], None] = '7edb7006f903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_llm_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_primary', sa.String(), nullable=True),
    sa.Column('provider_secondary', sa.String(), nullable=True),
    sa.Column('provider_chat', sa.String(), nullable=True),
    sa.Column('provider_vision', sa.String(), nullable=True),
    sa.Column('provider_suggestions', sa.String(), nullable=True),
    sa.Column('provider_embedding', sa.String(), nullable=True),
    sa.Column('model_primary', sa.String(), nullable=True),
    sa.Column('model_secondary', sa.String(), nullable=True),
    sa.Column('model_chat', sa.String(), nullable=True),
    sa.Column('model_vision', sa.String(), nullable=True),
    sa.Column('model_suggestions', sa.String(), nullable=True),
    sa.Column('model_embedding', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.Column('azure_openai_api_key', sa.String(), nullable=True),
    sa.Column('azure_openai_endpoint', sa.String(), nullable=True),
    sa.Column('anthropic_api_key', sa.String(), nullable=True),
    sa.Column('azure_foundry_api_key', sa.String(), nullable=True),
    sa.Column('azure_foundry_endpoint', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_llm_configs_tenant_id'), 'tenant_llm_configs', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_llm_configs_tenant_id'), table_name='tenant_llm_configs')
    op.drop_table('tenant_llm_configs')
    # ### end Alembic commands ###
