"""update spec_versions add authoritative and traceability columns

Revision ID: 7117eec8d379
Revises: 78ab203fa081
Create Date: 2026-02-22 09:51:47.942806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7117eec8d379'
down_revision: Union[str, Sequence[str], None] = '78ab203fa081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spec_versions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('spec_versions', sa.Column('is_authoritative', sa.Boolean(), nullable=True))
    op.add_column('spec_versions', sa.Column('claim_version_id', sa.UUID(), nullable=True))
    op.add_column('spec_versions', sa.Column('risk_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'spec_versions', 'claim_graph_versions', ['claim_version_id'], ['id'])
    op.create_foreign_key(None, 'spec_versions', 'risk_analysis_versions', ['risk_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spec_versions', type_='foreignkey')
    op.drop_constraint(None, 'spec_versions', type_='foreignkey')
    op.drop_column('spec_versions', 'risk_version_id')
    op.drop_column('spec_versions', 'claim_version_id')
    op.drop_column('spec_versions', 'is_authoritative')
    op.drop_column('spec_versions', 'description')
    # ### end Alembic commands ###
