"""add risk_analysis_versions table

Revision ID: 78ab203fa081
Revises: a3f1c8d92e47
Create Date: 2026-02-22 09:28:18.948231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78ab203fa081'
down_revision: Union[str, Sequence[str], None] = 'a3f1c8d92e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_analysis_versions',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_authoritative', sa.Boolean(), nullable=True),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claim_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_version_id'], ['claim_graph_versions.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_analysis_versions_matter_id'), 'risk_analysis_versions', ['matter_id'], unique=False)
    op.add_column('workstreams', sa.Column('active_risk_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workstreams', 'risk_analysis_versions', ['active_risk_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workstreams', type_='foreignkey')
    op.drop_column('workstreams', 'active_risk_version_id')
    op.drop_index(op.f('ix_risk_analysis_versions_matter_id'), table_name='risk_analysis_versions')
    op.drop_table('risk_analysis_versions')
    # ### end Alembic commands ###
