"""Add Matter Display Fields

Revision ID: 96cb835f696b
Revises: 78eb7b9a1f48
Create Date: 2026-02-19 23:00:07.174323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96cb835f696b'
down_revision: Union[str, Sequence[str], None] = '78eb7b9a1f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matters', sa.Column('inventors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('matters', sa.Column('assignee', sa.String(), nullable=True))
    op.add_column('matters', sa.Column('tech_domain', sa.String(), nullable=True))
    op.add_column('matters', sa.Column('defensibility_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matters', 'defensibility_score')
    op.drop_column('matters', 'tech_domain')
    op.drop_column('matters', 'assignee')
    op.drop_column('matters', 'inventors')
    # ### end Alembic commands ###
